round1 = [
    ('Austria', 'Romania'),
    ('Argentina', 'Singapore'),
    ('Russia', 'Brazil'),
    ('Vietnam', 'Italy'),
    ('Netherlands', 'Germany'),
    ('Indonesia', 'Norway'),
    ('Taiwan', 'Kazakhstan'),
    ('Finland', 'United Kingdom'),
    ('Bulgaria', 'Malaysia'),
    ('Belarus', 'Australia'),
    ('Czech Republic', 'Canada'),
    ('New Zealand', 'Portugal'),
    ('Mexico', 'Greece'),
    ('Hungary', 'Thailand'),
    ('Spain', 'Switzerland'),
    ('Philippines', 'France'),
    ('Turkey', 'South Korea'),
    ('Chile', 'Hong Kong'),
    ('Denmark', 'Peru'),
    ('Croatia', 'Ukraine'),
    ('Slovakia', 'Israel'),
    ('United States', 'China'),
    ('Sweden', 'Japan'),
    ('Belgium', 'Poland'),
]

round1_final_order = {
    ('Sweden', 'Japan') : [
        ('Warlock', 'Hunter'),
        ('Paladin', 'Shaman'),
        ('Priest', 'Rogue'),
        ('Mage', 'Warrior'),
        ('Shaman', 'Mage'),
    ],
    ('Slovakia', 'Israel') : [
        ('Rogue', 'Hunter'),
        ('Mage', 'Priest'),
        ('Shaman', 'Rogue'),
        ('Priest', 'Druid'),
        ('Warlock', 'Paladin'),
    ],
    ('Turkey', 'South Korea') : [
        ('Shaman', 'Warlock'),
        ('Hunter', 'Hunter'),
        ('Priest', 'Druid'),
        ('Warrior', 'Mage'),
        ('Paladin', 'Warrior'),
    ],
    ('Belarus', 'Australia') : [
        ('Rogue', 'Hunter'),
        ('Priest', 'Mage'),
        ('Hunter', 'Warlock'),
        ('Shaman', 'Priest'),
        ('Warrior', 'Paladin'),
    ],
    ('Indonesia', 'Norway') : [
        ('Warlock', 'Warrior'),
        ('Mage', 'Druid'),
        ('Warrior', 'Priest'),
        ('Paladin', 'Paladin'),
        ('Priest', 'Rogue'),
    ],
    ('Bulgaria', 'Malaysia') : [
        ('Druid', 'Warlock'),
        ('Warlock', 'Paladin'),
        ('Warrior', 'Rogue'),
        ('Rogue', 'Warrior'),
        ('Priest', 'Druid'),
    ],
    ('Philippines', 'France') : [
        ('Druid', 'Rogue'),
        ('Priest', 'Shaman'),
        ('Warlock', 'Warlock'),
        ('Paladin', 'Priest'),
        ('Shaman', 'Hunter'),
    ],
    ('Vietnam', 'Italy') : [
        ('Warlock', 'Warrior'),
        ('Priest', 'Hunter'),
        ('Mage', 'Paladin'),
        ('Rogue', 'Rogue'),
        ('Druid', 'Warlock'),
    ],
    ('Belgium', 'Poland') : [
        ('Hunter', 'Shaman'),
        ('Shaman', 'Mage'),
        ('Warlock', 'Warrior'),
        ('Mage', 'Paladin'),
        ('Paladin', 'Warlock'),
    ],
    ('Hungary', 'Thailand') : [
        ('Shaman', 'Hunter'),
        ('Druid', 'Shaman'),
        ('Mage', 'Mage'),
        ('Rogue', 'Rogue'),
        ('Warlock', 'Warrior'),
    ],
    ('Croatia', 'Ukraine') : [
        ('Warlock', 'Warlock'),
        ('Warrior', 'Warrior'),
        ('Hunter', 'Paladin'),
        ('Rogue', 'Rogue'),
        ('Mage', 'Shaman'),
    ],
    ('United States', 'China') : [
        ('Rogue', 'Mage'),
        ('Mage', 'Rogue'),
        ('Shaman', 'Druid'),
        ('Warlock', 'Priest'),
        ('Paladin', 'Warlock'),
    ],
    ('Austria', 'Romania') : [
        ('Warlock', 'Priest'),
        ('Hunter', 'Druid'),
        ('Shaman', 'Shaman'),
        ('Mage', 'Mage'),
        ('Warrior', 'Warlock'),
    ],
    ('Netherlands', 'Germany') : [
        ('Hunter', 'Warlock'),
        ('Paladin', 'Paladin'),
        ('Priest', 'Hunter'),
        ('Warrior', 'Druid'),
        ('Druid', 'Mage'),
    ],
    ('Finland', 'United Kingdom') : [
        ('Mage', 'Shaman'),
        ('Warrior', 'Rogue'),
        ('Shaman', 'Mage'),
        ('Warlock', 'Warrior'),
        ('Priest', 'Paladin'),
    ],
    ('Russia', 'Brazil') : [
        ('Warlock', 'Priest'),
        ('Mage', 'Paladin'),
        ('Shaman', 'Warlock'),
        ('Paladin', 'Warrior'),
        ('Warrior', 'Shaman'),
    ],
    ('Mexico', 'Greece') : [
        ('Priest', 'Druid'),
        ('Rogue', 'Mage'),
        ('Mage', 'Hunter'),
        ('Warrior', 'Priest'),
        ('Hunter', 'Warlock'),
    ],
    ('Czech Republic', 'Canada') : [
        ('Rogue', 'Warlock'),
        ('Shaman', 'Paladin'),
        ('Mage', 'Rogue'),
        ('Priest', 'Mage'),
        ('Warrior', 'Druid'),
    ],
    ('Spain', 'Switzerland') : [
        ('Priest', 'Hunter'),
        ('Druid', 'Mage'),
        ('Paladin', 'Rogue'),
        ('Shaman', 'Warrior'),
        ('Mage', 'Warlock'),
    ],
    ('New Zealand', 'Portugal') : [
        ('Rogue', 'Rogue'),
        ('Mage', 'Paladin'),
        ('Warlock', 'Druid'),
        ('Shaman', 'Mage'),
        ('Hunter', 'Priest'),
    ],
    ('Denmark', 'Peru') : [
        ('Warlock', 'Priest'),
        ('Shaman', 'Mage'),
        ('Mage', 'Warrior'),
        ('Hunter', 'Hunter'),
        ('Priest', 'Warlock'),
    ],
    ('Argentina', 'Singapore') : [
        ('Mage', 'Warlock'),
        ('Warlock', 'Druid'),
        ('Priest', 'Rogue'),
        ('Druid', 'Warrior'),
        ('Shaman', 'Mage'),
    ],
    ('Chile', 'Hong Kong') : [
        ('Paladin', 'Druid'),
        ('Rogue', 'Shaman'),
        ('Druid', 'Rogue'),
        ('Warrior', 'Priest'),
        ('Warlock', 'Mage'),
    ],
    ('Taiwan', 'Kazakhstan') : [
        ('Shaman', 'Rogue'),
        ('Warrior', 'Hunter'),
        ('Druid', 'Shaman'),
        ('Hunter', 'Paladin'),
        ('Rogue', 'Warlock'),
    ],
}

round1_scores = {
    ('Austria', 'Romania')    : (2,3),
    ('Argentina', 'Singapore')    : (0,3),
    ('Russia', 'Brazil')    : (2,3),
    ('Vietnam', 'Italy')    : (2,3),
    ('Netherlands', 'Germany')    : (1,3),
    ('Indonesia', 'Norway')    : (3,1),
    ('Taiwan', 'Kazakhstan')    : (3,2),
    ('Finland', 'United Kingdom')    : (3,2),
    ('Bulgaria', 'Malaysia')    : (3,2),
    ('Belarus', 'Australia')    : (3,1),
    ('Czech Republic', 'Canada')    : (3,2),
    ('New Zealand', 'Portugal')    : (3,2),
    ('Mexico', 'Greece')    : (2,3),
    ('Hungary', 'Thailand')    : (2,3),
    ('Spain', 'Switzerland')    : (3,1),
    ('Philippines', 'France')    : (1,3),
    ('Turkey', 'South Korea')    : (1,3),
    ('Chile', 'Hong Kong')    : (3,1),
    ('Denmark', 'Peru')    : (0,3),
    ('Croatia', 'Ukraine')    : (2,3),
    ('Slovakia', 'Israel')    : (3,1),
    ('United States', 'China')    : (2,3),
    ('Sweden', 'Japan')    : (3,2),
    ('Belgium', 'Poland')    : (1,3),
}


round2 = [
    ('New Zealand', 'Sweden'),
    ('Belarus', 'Finland'),
    ('Spain', 'Slovakia'),
    ('Greece', 'Brazil'),
    ('Indonesia', 'Czech Republic'),
    ('Italy', 'Bulgaria'),
    ('Germany', 'Romania'),
    ('Poland', 'South Korea'),
    ('China', 'France'),
    ('Thailand', 'Taiwan'),
    ('Chile', 'Ukraine'),
    ('Singapore', 'Peru'),
    ('Norway', 'Israel'),
    ('Hungary', 'Russia'),
    ('United Kingdom', 'United States'),
    ('Croatia', 'Belgium'),
    ('Malaysia', 'Hong Kong'),
    ('Austria', 'Switzerland'),
    ('Philippines', 'Vietnam'),
    ('Turkey', 'Netherlands'),
    ('Denmark', 'Argentina'),
    ('Japan', 'Portugal'),
    ('Kazakhstan', 'Mexico'),
    ('Canada', 'Australia'),
]

round2_final_order = {
    ('Norway', 'Israel') : [
        ('Hunter', 'Shaman'),
        ('Priest', 'Druid'),
        ('Druid', 'Hunter'),
        ('Shaman', 'Priest'),
        ('Mage', 'Warlock')
    ],
    ('Denmark', 'Argentina') : [
        ('Rogue', 'Rogue'),
        ('Druid', 'Shaman'),
        ('Warrior', 'Paladin'),
        ('Mage', 'Mage'),
        ('Hunter', 'Warrior')
    ],
    ('New Zealand', 'Sweden') : [
        ('Druid', 'Mage'),
        ('Mage', 'Warlock'),
        ('Warlock', 'Rogue'),
        ('Warrior', 'Paladin'),
        ('Hunter', 'Priest')
    ],
    ('Belarus', 'Finland') : [
        ('Shaman', 'Paladin'),
        ('Mage', 'Warrior'),
        ('Hunter', 'Hunter'),
        ('Warlock', 'Rogue'),
        ('Warrior', 'Shaman')
    ],
    ('Spain', 'Slovakia') : [
        ('Paladin', 'Mage'),
        ('Druid', 'Hunter'),
        ('Warrior', 'Shaman'),
        ('Priest', 'Warlock'),
        ('Hunter', 'Warrior')
    ],
    ('Greece', 'Brazil') : [
        ('Hunter', 'Mage'),
        ('Priest', 'Shaman'),
        ('Paladin', 'Warrior'),
        ('Rogue', 'Paladin'),
        ('Warrior', 'Hunter')
    ],
    ('Indonesia', 'Czech Republic') : [
        ('Rogue', 'Priest'),
        ('Mage', 'Rogue'),
        ('Paladin', 'Warlock'),
        ('Druid', 'Warrior'),
        ('Warrior', 'Shaman')
    ],
    ('Italy', 'Bulgaria') : [
        ('Warlock', 'Priest'),
        ('Priest', 'Warrior'),
        ('Paladin', 'Paladin'),
        ('Druid', 'Hunter'),
        ('Hunter', 'Mage')
    ],
    ('Germany', 'Romania') : [
        ('Druid', 'Rogue'),
        ('Priest', 'Warlock'),
        ('Shaman', 'Priest'),
        ('Hunter', 'Warrior'),
        ('Warlock', 'Mage')
    ],
    ('Poland', 'South Korea') : [
        ('Paladin', 'Hunter'),
        ('Shaman', 'Warlock'),
        ('Warrior', 'Shaman'),
        ('Hunter', 'Rogue'),
        ('Warlock', 'Warrior')
    ],
    ('China', 'France') : [
        ('Paladin', 'Rogue'),
        ('Warlock', 'Warrior'),
        ('Mage', 'Mage'),
        ('Warrior', 'Warlock'),
        ('Druid', 'Hunter')
    ],
    ('Thailand', 'Taiwan') : [
        ('Hunter', 'Druid'),
        ('Shaman', 'Paladin'),
        ('Mage', 'Rogue'),
        ('Druid', 'Mage'),
        ('Paladin', 'Priest')
    ],
    ('Chile', 'Ukraine') : [
        ('Hunter', 'Hunter'),
        ('Mage', 'Shaman'),
        ('Warrior', 'Warrior'),
        ('Paladin', 'Paladin'),
        ('Druid', 'Druid')
    ],
    ('Singapore', 'Peru') : [
        ('Paladin', 'Priest'),
        ('Hunter', 'Mage'),
        ('Priest', 'Warrior'),
        ('Rogue', 'Druid'),
        ('Mage', 'Warlock'),
    ],
    ('Hungary', 'Russia') : [
        ('Paladin', 'Shaman'),
        ('Warrior', 'Rogue'),
        ('Rogue', 'Hunter'),
        ('Priest', 'Warlock'),
        ('Mage', 'Priest')
    ],
    ('United Kingdom', 'United States') : [
        ('Paladin', 'Mage'),
        ('Rogue', 'Priest'),
        ('Warlock', 'Druid'),
        ('Hunter', 'Shaman'),
        ('Shaman', 'Paladin')
    ],
    ('Croatia', 'Belgium') : [
        ('Warlock', 'Shaman'),
        ('Paladin', 'Warrior'),
        ('Priest', 'Mage'),
        ('Rogue', 'Warlock'),
        ('Warrior', 'Paladin')
    ],
    ('Malaysia', 'Hong Kong') : [
        ('Paladin', 'Mage'),
        ('Shaman', 'Rogue'),
        ('Druid', 'Warlock'),
        ('Warlock', 'Paladin'),
        ('Rogue', 'Druid')
    ],
    ('Austria', 'Switzerland') : [
        ('Priest', 'Druid'),
        ('Mage', 'Priest'),
        ('Warlock', 'Warrior'),
        ('Rogue', 'Paladin'),
        ('Shaman', 'Warlock')
    ],
    ('Philippines', 'Vietnam') : [
        ('Rogue', 'Warlock'),
        ('Warrior', 'Mage'),
        ('Hunter', 'Priest'),
        ('Druid', 'Shaman'),
        ('Paladin', 'Paladin')
    ],
    ('Turkey', 'Netherlands') : [
        ('Shaman', 'Shaman'),
        ('Paladin', 'Warrior'),
        ('Priest', 'Druid'),
        ('Warrior', 'Paladin'),
        ('Druid', 'Priest')
    ],
    ('Japan', 'Portugal') : [
        ('Warrior', 'Warrior'),
        ('Mage', 'Rogue'),
        ('Paladin', 'Shaman'),
        ('Druid', 'Warlock'),
        ('Warlock', 'Mage')
    ],
    ('Kazakhstan', 'Mexico') : [
        ('Mage', 'Warlock'),
        ('Warlock', 'Priest'),
        ('Shaman', 'Paladin'),
        ('Paladin', 'Warrior'),
        ('Hunter', 'Druid')
    ],
    ('Canada', 'Australia') : [
        ('Warlock', 'Warlock'),
        ('Paladin', 'Mage'),
        ('Mage', 'Shaman'),
        ('Priest', 'Druid'),
        ('Rogue', 'Paladin')
    ],
}

round2_scores = {
    ('New Zealand', 'Sweden')         : (3,2),
    ('Belarus', 'Finland')         : (3,1),
    ('Spain', 'Slovakia')         : (3,2),
    ('Greece', 'Brazil')         : (1,3),
    ('Indonesia', 'Czech Republic')         : (2,3),
    ('Italy', 'Bulgaria')         : (3,1),
    ('Germany', 'Romania')         : (2,3),
    ('Poland', 'South Korea')         : (3,2),
    ('China', 'France')         : (3,2),
    ('Thailand', 'Taiwan')         : (3,2),
    ('Chile', 'Ukraine')         : (0,3),
    ('Singapore', 'Peru')         : (3,1),
    ('Norway', 'Israel')         : (3,0),
    ('Hungary', 'Russia')         : (0,3),
    ('United Kingdom', 'United States')         : (3,1),
    ('Croatia', 'Belgium')         : (1,3),
    ('Malaysia', 'Hong Kong')         : (2,3),
    ('Austria', 'Switzerland')         : (0,3),
    ('Philippines', 'Vietnam')         : (1,3),
    ('Turkey', 'Netherlands')         : (1,3),
    ('Denmark', 'Argentina')         : (3,0),
    ('Japan', 'Portugal')         : (1,3),
    ('Kazakhstan', 'Mexico')         : (3,2),
    ('Canada', 'Australia')         : (3,1),
}

round3 = [
    ('China', 'Poland'),
    ('Italy', 'Spain'),
    ('Ukraine', 'Belarus'),
    ('Brazil', 'Singapore'),
    ('Czech Republic', 'Romania'),
    ('Taiwan', 'New Zealand'),
    ('Greece', 'Germany'),
    ('Bulgaria', 'Denmark'),
    ('Chile', 'Slovakia'),
    ('Peru', 'Netherlands'),
    ('United Kingdom', 'Sweden'),
    ('Canada', 'Vietnam'),
    ('Thailand', 'France'),
    ('Russia', 'Kazakhstan'),
    ('Belgium', 'Hong Kong'),
    ('Norway', 'Portugal'),
    ('Switzerland', 'Indonesia'),
    ('South Korea', 'Finland'),
    ('Hungary', 'Malaysia'),
    ('Croatia', 'Japan'),
    ('Australia', 'Argentina'),
    ('Israel', 'Philippines'),
    ('United States', 'Turkey'),
    ('Mexico', 'Austria'),
]

round3_final_order = {
    ('China', 'Poland') : [
        ('Rogue', 'Druid'),
        ('Paladin', 'Hunter'),
        ('Warrior', 'Warrior'),
        ('Shaman', 'Rogue'),
        ('Warlock', 'Mage'),
    ],
    ('Italy', 'Spain') : [
        ('Rogue', 'Mage'),
        ('Warrior', 'Hunter'),
        ('Priest', 'Priest'),
        ('Mage', 'Rogue'),
        ('Paladin', 'Warlock'),
    ],
    ('Ukraine', 'Belarus') : [
        ('Hunter', 'Warrior'),
        ('Rogue', 'Mage'),
        ('Mage', 'Druid'),
        ('Warrior', 'Shaman'),
        ('Priest', 'Paladin'),
    ],
    ('Brazil', 'Singapore') : [
        ('Mage', 'Priest'),
        ('Priest', 'Shaman'),
        ('Druid', 'Paladin'),
        ('Paladin', 'Warlock'),
        ('Hunter', 'Warrior'),
    ],
    ('Czech Republic', 'Romania') : [
        ('Warlock', 'Paladin'),
        ('Mage', 'Mage'),
        ('Shaman', 'Rogue'),
        ('Warrior', 'Priest'),
        ('Priest', 'Druid'),
    ],
    ('Taiwan', 'New Zealand') : [
        ('Rogue', 'Mage'),
        ('Paladin', 'Druid'),
        ('Warlock', 'Hunter'),
        ('Warrior', 'Rogue'),
        ('Shaman', 'Shaman'),
    ],
    ('Greece', 'Germany') : [
        ('Druid', 'Shaman'),
        ('Warrior', 'Rogue'),
        ('Hunter', 'Druid'),
        ('Shaman', 'Warrior'),
        ('Mage', 'Paladin'),
    ],
    ('Bulgaria', 'Denmark') : [
        ('Hunter', 'Priest'),
        ('Priest', 'Warlock'),
        ('Warrior', 'Mage'),
        ('Rogue', 'Hunter'),
        ('Paladin', 'Druid'),
    ],
    ('Chile', 'Slovakia') : [
        ('Paladin', 'Druid'),
        ('Rogue', 'Rogue'),
        ('Hunter', 'Shaman'),
        ('Priest', 'Warrior'),
        ('Druid', 'Warlock'),
    ],
    ('Peru', 'Netherlands') : [
        ('Mage', 'Priest'),
        ('Warlock', 'Shaman'),
        ('Paladin', 'Warlock'),
        ('Warrior', 'Druid'),
        ('Priest', 'Mage'),

    ],
    ('United Kingdom', 'Sweden') : [
        ('Mage', 'Priest'),
        ('Paladin', 'Rogue'),
        ('Hunter', 'Warlock'),
        ('Priest', 'Mage'),
        ('Druid', 'Shaman'),
    ],
    ('Canada', 'Vietnam') : [
        ('Rogue', 'Paladin'),
        ('Warrior', 'Shaman'),
        ('Druid', 'Mage'),
        ('Mage', 'Warrior'),
        ('Warlock', 'Priest'),
    ],
    ('Thailand', 'France') : [
        ('Druid', 'Druid'),
        ('Warrior', 'Priest'),
        ('Hunter', 'Shaman'),
        ('Paladin', 'Paladin'),
        ('Priest', 'Hunter'),
    ],
    ('Russia', 'Kazakhstan') : [
        ('Mage', 'Priest'),
        ('Priest', 'Mage'),
        ('Rogue', 'Hunter'),
        ('Shaman', 'Shaman'),
        ('Warrior', 'Warrior'),
    ],
    ('Belgium', 'Hong Kong') : [
        ('Druid', 'Rogue'),
        ('Mage', 'Hunter'),
        ('Shaman', 'Shaman'),
        ('Rogue', 'Warrior'),
        ('Paladin', 'Priest'),
    ],
    ('Norway', 'Portugal') : [
        ('Mage', 'Priest'),
        ('Druid', 'Shaman'),
        ('Hunter', 'Mage'),
        ('Warrior', 'Warrior'),
        ('Paladin', 'Druid'),
    ],
    ('Switzerland', 'Indonesia') : [
        ('Hunter', 'Shaman'),
        ('Warlock', 'Mage'),
        ('Priest', 'Warrior'),
        ('Rogue', 'Druid'),
        ('Druid', 'Priest'),

    ],
    ('South Korea', 'Finland') : [
        ('Hunter', 'Hunter'),
        ('Priest', 'Mage'),
        ('Mage', 'Paladin'),
        ('Shaman', 'Shaman'),
        ('Rogue', 'Warlock'),
    ],
    ('Hungary', 'Malaysia') : [
        ('Hunter', 'Warlock'),
        ('Paladin', 'Druid'),
        ('Shaman', 'Shaman'),
        ('Warrior', 'Mage'),
        ('Warlock', 'Hunter'),
    ],
    ('Croatia', 'Japan') : [
        ('Warrior', 'Shaman'),
        ('Priest', 'Priest'),
        ('Warlock', 'Paladin'),
        ('Mage', 'Warlock'),
        ('Shaman', 'Hunter'),   
    ],
    ('Australia', 'Argentina') : [
        ('Priest', 'Hunter'),
        ('Warrior', 'Warlock'),
        ('Hunter', 'Mage'),
        ('Warlock', 'Warrior'),
        ('Shaman', 'Priest'),
    ],
    ('Israel', 'Philippines') : [
        ('Warlock', 'Priest'),
        ('Shaman', 'Druid'),
        ('Warrior', 'Warrior'),
        ('Mage', 'Paladin'),
        ('Paladin', 'Warlock'),
    ],
    ('United States', 'Turkey') : [
        ('Druid', 'Priest'),
        ('Paladin', 'Shaman'),
        ('Priest', 'Warlock'),
        ('Mage', 'Warrior'),
        ('Rogue', 'Mage'),
    ],
    ('Mexico', 'Austria') : [
        ('Mage', 'Rogue'),
        ('Warlock', 'Priest'),
        ('Paladin', 'Warlock'),
        ('Hunter', 'Druid'),
        ('Warrior', 'Hunter'),
    ],
}

round3_scores = {}

round4 = [
    ('Brazil', 'Spain'),
    ('Ukraine', 'Czech Republic'),
    ('Taiwan', 'China'),
    ('Thailand', 'Hong Kong'),
    ('Poland', 'Vietnam'),
    ('Italy', 'Netherlands'),
    ('Bulgaria', 'Russia'),
    ('Belarus', 'United Kingdom'),
    ('New Zealand', 'Singapore'),
    ('Chile', 'Norway'),
    ('Romania', 'Switzerland'),
    ('Germany', 'South Korea'),
    ('Portugal', 'France'),
    ('Belgium', 'Israel'),
    ('Peru', 'Australia'),
    ('Finland', 'Sweden'),
    ('Slovakia', 'Canada'),
    ('Japan', 'Austria'),
    ('Hungary', 'Denmark'),
    ('Kazakhstan', 'United States'),
    ('Indonesia', 'Greece'),
]

round4_final_order = {
    ('New Zealand', 'Singapore') : [
        ('Hunter', 'Shaman'),
        ('Druid', 'Warrior'),
        ('Rogue', 'Druid'),
        ('Paladin', 'Priest'),
        ('Warlock', 'Mage'),
    ],
    ('Finland', 'Sweden') : [
        ('Rogue', 'Paladin'),
        ('Shaman', 'Shaman'),
        ('Warrior', 'Druid'),
        ('Priest', 'Hunter'),
        ('Mage', 'Warlock'),
    ],
    ('Japan', 'Austria') : [
        ('Warlock', 'Rogue'),
        ('Shaman', 'Hunter'),
        ('Mage', 'Priest'),
        ('Warrior', 'Warlock'),
        ('Paladin', 'Warrior'),
    ],
    ('Hungary', 'Denmark') : [
        ('Hunter', 'Hunter'),
        ('Warlock', 'Paladin'),
        ('Warrior', 'Druid'),
        ('Paladin', 'Warlock'),
        ('Priest', 'Priest'),
    ],
    ('Poland', 'Vietnam') : [
        ('Rogue', 'Rogue'),
        ('Druid', 'Hunter'),
        ('Shaman', 'Warrior'),
        ('Mage', 'Mage'),
        ('Warrior', 'Paladin'),
    ],
    ('Germany', 'South Korea') : [
        ('Warlock', 'Shaman'),
        ('Shaman', 'Paladin'),
        ('Hunter', 'Priest'),
        ('Priest', 'Warrior'),
        ('Mage', 'Rogue'),
    ],
    ('Italy', 'Netherlands') : [
        ('Hunter', 'Rogue'),
        ('Paladin', 'Shaman'),
        ('Warrior', 'Warrior'),
        ('Rogue', 'Hunter'),
        ('Priest', 'Mage'),
    ],
    ('Belgium', 'Israel') : [
        ('Druid', 'Hunter'),
        ('Warrior', 'Shaman'),
        ('Paladin', 'Warrior'),
        ('Priest', 'Warlock'),
        ('Hunter', 'Druid'),
    ],
    ('Ukraine', 'Czech Republic') : [
        ('Paladin', 'Hunter'),
        ('Mage', 'Paladin'),
        ('Hunter', 'Mage'),
        ('Druid', 'Rogue'),
        ('Shaman', 'Shaman'),
    ],
    ('Slovakia', 'Canada') : [
        ('Rogue', 'Warlock'),
        ('Shaman', 'Priest'),
        ('Warlock', 'Shaman'),
        ('Paladin', 'Rogue'),
        ('Mage', 'Mage'),
    ],
    ('Taiwan', 'China') : [
        ('Warrior', 'Warrior'),
        ('Hunter', 'Mage'),
        ('Shaman', 'Shaman'),
        ('Mage', 'Priest'),
        ('Rogue', 'Warlock'),
    ],
    ('Bulgaria', 'Russia') : [
        ('Paladin', 'Mage'),
        ('Hunter', 'Hunter'),
        ('Warrior', 'Shaman'),
        ('Rogue', 'Warrior'),
        ('Priest', 'Priest'),
    ],
    ('Indonesia', 'Greece') : [
        ('Paladin', 'Warlock'),
        ('Warlock', 'Mage'),
        ('Warrior', 'Shaman'),
        ('Priest', 'Hunter'),
        ('Mage', 'Warrior'),
    ],
    ('Romania', 'Switzerland') : [
        ('Priest', 'Priest'),
        ('Warrior', 'Rogue'),
        ('Hunter', 'Druid'),
        ('Druid', 'Mage'),
        ('Paladin', 'Paladin'),
    ],
    ('Belarus', 'United Kingdom') : [
        ('Hunter', 'Rogue'),
        ('Mage', 'Hunter'),
        ('Warrior', 'Druid'),
        ('Paladin', 'Priest'),
        ('Druid', 'Warlock'),
    ],
    ('Kazakhstan', 'United States') : [
        ('Shaman', 'Shaman'),
        ('Hunter', 'Rogue'),
        ('Mage', 'Paladin'),
        ('Rogue', 'Warrior'),
        ('Warlock', 'Priest'),
    ],
    ('Chile', 'Norway') : [
        ('Shaman', 'Shaman'),
        ('Warrior', 'Priest'),
        ('Warlock', 'Warlock'),
        ('Paladin', 'Rogue'),
        ('Hunter', 'Hunter'),
    ],
    ('Portugal', 'France') : [
        ('Shaman', 'Warlock'),
        ('Priest', 'Druid'),
        ('Druid', 'Shaman'),
        ('Warrior', 'Warrior'),
        ('Paladin', 'Priest'),
    ],
    ('Brazil', 'Spain') : [
        ('Priest', 'Mage'),
        ('Hunter', 'Warrior'),
        ('Mage', 'Hunter'),
        ('Druid', 'Priest'),
        ('Warlock', 'Druid'),
    ],
    ('Peru', 'Australia') : [
        ('Hunter', 'Shaman'),
        ('Warrior', 'Rogue'),
        ('Warlock', 'Priest'),
        ('Mage', 'Mage'),
        ('Paladin', 'Druid'),
    ],
    ('Thailand', 'Hong Kong') : [
        ('Shaman', 'Druid'),
        ('Priest', 'Warlock'),
        ('Druid', 'Rogue'),
        ('Rogue', 'Hunter'),
        ('Mage', 'Mage'),
    ],
}

round4_scores = {}

round5 = [
    ('Brazil', 'China'),
    ('Ukraine', 'Taiwan'),
    ('Bulgaria', 'Spain'),
    ('Poland', 'Chile'),
    ('Hong Kong', 'Switzerland'),
    ('Singapore', 'Netherlands'),
    ('United Kingdom', 'South Korea'),
    ('Czech Republic', 'Germany'),
    ('Canada', 'Japan'),
    ('Belgium', 'Peru'),
    ('Italy', 'New Zealand'),
    ('United States', 'Denmark'),
    ('Belarus', 'Indonesia'),
    ('Vietnam', 'Thailand'),
    ('Portugal', 'Romania'),
    ('Russia', 'Norway'),
]

round5_final_order = {
    ('Ukraine', 'Taiwan') : [
        ('Druid', 'Warlock'),
        ('Rogue', 'Paladin'),
        ('Hunter', 'Druid'),
        ('Warlock', 'Warrior'),
        ('Mage', 'Shaman'),
    ],
    ('Italy', 'New Zealand') : [
        ('Warlock', 'Druid'),
        ('Paladin', 'Mage'),
        ('Warrior', 'Rogue'),
        ('Rogue', 'Paladin'),
        ('Mage', 'Shaman'),
    ],
    ('Belarus', 'Indonesia') : [
        ('Shaman', 'Druid'),
        ('Mage', 'Rogue'),
        ('Rogue', 'Warlock'),
        ('Hunter', 'Priest'),
        ('Warrior', 'Mage'),
    ],
    ('Brazil', 'China') : [
        ('Mage', 'Druid'),
        ('Rogue', 'Shaman'),
        ('Hunter', 'Warlock'),
        ('Priest', 'Hunter'),
        ('Warrior', 'Warrior'),
    ],
    ('Hong Kong', 'Switzerland') : [
        ('Warrior', 'Rogue'),
        ('Rogue', 'Mage'),
        ('Hunter', 'Hunter'),
        ('Mage', 'Druid'),
        ('Shaman', 'Priest'),
    ],
    ('Singapore', 'Netherlands') : [
        ('Priest', 'Paladin'),
        ('Druid', 'Mage'),
        ('Rogue', 'Warrior'),
        ('Warlock', 'Druid'),
        ('Mage', 'Shaman'),
    ],
    #('Belgium', 'Peru') : [
    #    ('Rogue', 'Hunter'),
    #    ('Druid', 'Paladin'),
    #    ('Warlock', 'Rogue'),
    #],
    ('Portugal', 'Romania') : [
        ('Warlock', 'Warlock'),
        ('Priest', 'Hunter'),
        ('Shaman', 'Druid'),
        ('Druid', 'Warrior'),
        ('Warrior', 'Shaman'),
    ],
    ('United Kingdom', 'South Korea') : [
        ('Priest', 'Rogue'),
        ('Warlock', 'Paladin'),
        ('Warrior', 'Mage'),
        ('Druid', 'Hunter'),
        ('Paladin', 'Shaman'),
    ],
    ('Bulgaria', 'Spain') : [
        ('Warlock', 'Druid'),
        ('Shaman', 'Hunter'),
        ('Mage', 'Warrior'),
        ('Hunter', 'Shaman'),
        ('Priest', 'Mage'),
    ],
    ('Poland', 'Chile') : [
        ('Rogue', 'Shaman'),
        ('Shaman', 'Warlock'),
        ('Priest', 'Druid'),
        ('Paladin', 'Rogue'),
        ('Druid', 'Mage'),
    ],
    ('Russia', 'Norway') : [
        ('Mage', 'Warrior'),
        ('Priest', 'Warlock'),
        ('Shaman', 'Rogue'),
        ('Druid', 'Paladin'),
        ('Hunter', 'Shaman'),
    ],
    ('Czech Republic', 'Germany') : [
        ('Warlock', 'Priest'),
        ('Mage', 'Mage'),
        ('Priest', 'Hunter'),
        ('Shaman', 'Paladin'),
        ('Warrior', 'Shaman'),
    ],
    ('United States', 'Denmark') : [
        ('Druid', 'Paladin'),
        ('Priest', 'Shaman'),
        ('Mage', 'Druid'),
        ('Hunter', 'Warlock'),
        ('Warlock', 'Mage'),
    ],
    ('Canada', 'Japan') : [
        ('Priest', 'Paladin'),
        ('Shaman', 'Druid'),
        ('Druid', 'Hunter'),
        ('Warlock', 'Warlock'),
        ('Hunter', 'Priest'),
    ],
    ('Vietnam', 'Thailand') : [
        ('Priest', 'Shaman'),
        ('Warlock', 'Rogue'),
        ('Druid', 'Warrior'),
        ('Rogue', 'Mage'),
        ('Mage', 'Warlock'),
    ],
}

round6 = [
    ('Brazil', 'Switzerland'),
    ('China', 'Ukraine'),
    ('Taiwan', 'United Kingdom'),
    ('Singapore', 'Chile'),
    ('Bulgaria', 'Czech Republic'),
    ('Poland', 'Netherlands'),
    ('Belgium', 'Spain'),
    ('Portugal', 'Canada'),
    ('South Korea', 'United States'),
    ('Thailand', 'Norway'),
    ('Germany', 'Indonesia'),
    ('Hong Kong', 'Sweden'),
]

round6_final_order = {
    ('Brazil', 'Switzerland') : [
        ('Warlock', 'Warrior'),
        ('Warrior', 'Hunter'),
        ('Shaman', 'Warlock'),
        ('Rogue', 'Paladin'),
        ('Paladin', 'Druid'),
    ],
    ('China', 'Ukraine') : [
        ('Shaman', 'Hunter'),
        ('Druid', 'Shaman'),
        ('Warlock', 'Warrior'),
        ('Warrior', 'Priest'),
        ('Paladin', 'Druid'),
    ],
    ('Taiwan', 'United Kingdom') : [
        ('Warlock', 'Paladin'),
        ('Priest', 'Shaman'),
        ('Hunter', 'Hunter'),
        ('Rogue', 'Druid'),
        ('Shaman', 'Priest'),
    ],
    ('Singapore', 'Chile') : [
        ('Priest', 'Shaman'),
        ('Hunter', 'Hunter'),
        ('Warrior', 'Druid'),
        ('Warlock', 'Warlock'),
        ('Shaman', 'Warrior'),
    ],
    ('Bulgaria', 'Czech Republic') : [
        ('Paladin', 'Paladin'),
        ('Warlock', 'Shaman'),
        ('Shaman', 'Warlock'),
        ('Priest', 'Rogue'),
        ('Mage', 'Priest'),
    ],
    ('Poland', 'Netherlands') : [
        ('Mage', 'Druid'),
        ('Warrior', 'Mage'),
        ('Druid', 'Hunter'),
        ('Priest', 'Paladin'),
        ('Shaman', 'Shaman'),
    ],
    ('Belgium', 'Spain') : [
        ('Warrior', 'Warlock'),
        ('Warlock', 'Priest'),
        ('Shaman', 'Shaman'),
        ('Hunter', 'Warrior'),
        ('Paladin', 'Mage'),
    ],
    ('Portugal', 'Canada') : [
        ('Shaman', 'Mage'),
        ('Warlock', 'Druid'),
        ('Rogue', 'Warrior'),
        ('Paladin', 'Paladin'),
        ('Hunter', 'Shaman'),
    ],
    ('South Korea', 'United States') : [
        ('Shaman', 'Rogue'),
        ('Warlock', 'Mage'),
        ('Warrior', 'Warrior'),
        ('Rogue', 'Hunter'),
        ('Hunter', 'Shaman'),
    ],
    ('Thailand', 'Norway') : [
        ('Priest', 'Rogue'),
        ('Rogue', 'Paladin'),
        ('Hunter', 'Druid'),
        ('Mage', 'Priest'),
        ('Paladin', 'Warlock'),
    ],
    ('Germany', 'Indonesia') : [
        ('Warlock', 'Shaman'),
        ('Druid', 'Priest'),
        ('Hunter', 'Hunter'),
        ('Mage', 'Mage'),
        ('Shaman', 'Warrior'),
    ],
    ('Hong Kong', 'Sweden') : [
        ('Druid', 'Mage'),
        ('Priest', 'Druid'),
        ('Mage', 'Paladin'),
        ('Rogue', 'Priest'),
        ('Hunter', 'Hunter'),
    ],
}

round7 = [
    ('Brazil', 'Portugal'),
    ('Chile', 'Spain'),
    ('Bulgaria', 'Netherlands'),
    ('United Kingdom', 'Hong Kong'),
    ('Singapore', 'United States'),
    ('Taiwan', 'New Zealand'),
    ('Ukraine', 'Norway'),
    ('China', 'Switzerland'),
]

round7_final_order = {
    ('Brazil', 'Portugal') : [
        ('Warrior', 'Priest'),
        ('Priest', 'Druid'),
        ('Hunter', 'Paladin'),
        ('Paladin', 'Warlock'),
        ('Shaman', 'Warrior'),
    ],
    ('Chile', 'Spain') : [
        ('Priest', 'Rogue'),
        ('Warrior', 'Warrior'),
        ('Hunter', 'Druid'),
        ('Mage', 'Shaman'),
        ('Warlock', 'Mage'),
    ],
    ('Bulgaria', 'Netherlands') : [
        ('Hunter', 'Paladin'),
        ('Warrior', 'Priest'),
        ('Mage', 'Warrior'),
        ('Paladin', 'Warlock'),
        ('Druid', 'Mage'),
    ],
    ('United Kingdom', 'Hong Kong') : [
        ('Priest', 'Priest'),
        ('Paladin', 'Paladin'),
        ('Warlock', 'Rogue'),
        ('Druid', 'Hunter'),
        ('Rogue', 'Shaman'),
    ],
    ('Singapore', 'United States') : [
        ('Hunter', 'Druid'),
        ('Priest', 'Shaman'),
        ('Warrior', 'Hunter'),
        ('Mage', 'Warlock'),
        ('Warlock', 'Paladin'),
    ],
    ('Taiwan', 'New Zealand') : [
        ('Rogue', 'Paladin'),
        ('Druid', 'Hunter'),
        ('Mage', 'Priest'),
        ('Shaman', 'Warlock'),
        ('Paladin', 'Rogue'),
    ],
    ('Ukraine', 'Norway') : [
        ('Mage', 'Warlock'),
        ('Warrior', 'Paladin'),
        ('Hunter', 'Warrior'),
        ('Druid', 'Shaman'),
        ('Warlock', 'Hunter'),
    ],
    ('China', 'Switzerland') : [
        ('Warlock', 'Rogue'),
        ('Druid', 'Mage'),
        ('Shaman', 'Shaman'),
        ('Rogue', 'Warlock'),
        ('Warrior', 'Priest'),
    ],
}

round8 = [
    ('Portugal', 'Spain'),
    ('Brazil', 'Chile'),
    ('Bulgaria', 'United Kingdom'),
    ('Hong Kong', 'Netherlands'),
    ('New Zealand', 'Singapore'),
    ('United States', 'Taiwan'),
    ('Norway', 'China'),
    ('Ukraine', 'Switzerland'),
]

round8_final_order = {
    ('Hong Kong', 'Netherlands') : [
        ('Warlock', 'Rogue'),
        ('Warrior', 'Mage'),
        ('Shaman', 'Paladin'),
        ('Paladin', 'Shaman'),
        ('Rogue', 'Druid'),
    ],
    ('Portugal', 'Spain') : [
        ('Warlock', 'Paladin'),
        ('Paladin', 'Shaman'),
        ('Druid', 'Druid'),
        ('Priest', 'Hunter'),
        ('Warrior', 'Warrior'),
    ],
    ('Brazil', 'Chile') : [
        ('Warlock', 'Druid'),
        ('Shaman', 'Priest'),
        ('Hunter', 'Warlock'),
        ('Druid', 'Shaman'),
        ('Rogue', 'Warrior'),
    ],
    ('Bulgaria', 'United Kingdom') : [
        ('Mage', 'Paladin'),
        ('Hunter', 'Warrior'),
        ('Shaman', 'Hunter'),
        ('Priest', 'Druid'),
        ('Warrior', 'Warlock'),
    ],
    ('New Zealand', 'Singapore') : [
        ('Shaman', 'Mage'),
        ('Hunter', 'Priest'),
        ('Warlock', 'Paladin'),
        ('Paladin', 'Warrior'),
        ('Druid', 'Hunter'),
    ],
    ('United States', 'Taiwan') : [
        ('Druid', 'Rogue'),
        ('Hunter', 'Mage'),
        ('Mage', 'Shaman'),
        ('Priest', 'Warlock'),
        ('Warlock', 'Druid'),
    ],
    ('Norway', 'China') : [
        ('Hunter', 'Shaman'),
        ('Warrior', 'Priest'),
        ('Priest', 'Druid'),
        ('Rogue', 'Rogue'),
        ('Paladin', 'Paladin'),
    ],
    ('Ukraine', 'Switzerland') : [
        ('Mage', 'Priest'),
        ('Warrior', 'Warrior'),
        ('Druid', 'Mage'),
        ('Shaman', 'Hunter'),
        ('Hunter', 'Druid'),
    ],
}

round9 = [
    ('Brazil', 'Portugal'),
    ('Hong Kong', 'United Kingdom'),
    ('Taiwan', 'Singapore'),
    ('Norway', 'Ukraine'),
]

round9_final_order = {
    ('Brazil', 'Portugal') : [
        ('Hunter', 'Druid'),
        ('Priest', 'Priest'),
        ('Paladin', 'Warlock'),
        ('Warrior', 'Paladin'),
        ('Shaman', 'Warrior'),
    ],
    ('Hong Kong', 'United Kingdom') : [
        ('Priest', 'Hunter'),
        ('Warrior', 'Paladin'),
        ('Shaman', 'Shaman'),
        ('Rogue', 'Druid'),
        ('Warlock', 'Mage'),
    ],
    ('Taiwan', 'Singapore') : [
        ('Warlock', 'Priest'),
        ('Hunter', 'Paladin'),
        ('Warrior', 'Hunter'),
        ('Mage', 'Rogue'),
        ('Shaman', 'Druid'),
    ],
    ('Norway', 'Ukraine') : [
        ('Shaman', 'Warrior'),
        ('Priest', 'Warlock'),
        ('Warrior', 'Druid'),
        ('Hunter', 'Mage'),
        ('Mage', 'Hunter'),
    ],
}
