round1 = [
    ('Austria', 'Romania'),
    ('Argentina', 'Singapore'),
    ('Russia', 'Brazil'),
    ('Vietnam', 'Italy'),
    ('Netherlands', 'Germany'),
    ('Indonesia', 'Norway'),
    ('Taiwan', 'Kazakhstan'),
    ('Finland', 'United Kingdom'),
    ('Bulgaria', 'Malaysia'),
    ('Belarus', 'Australia'),
    ('Czech Republic', 'Canada'),
    ('New Zealand', 'Portugal'),
    ('Mexico', 'Greece'),
    ('Hungary', 'Thailand'),
    ('Spain', 'Switzerland'),
    ('Philippines', 'France'),
    ('Turkey', 'South Korea'),
    ('Chile', 'Hong Kong'),
    ('Denmark', 'Peru'),
    ('Croatia', 'Ukraine'),
    ('Slovakia', 'Israel'),
    ('United States', 'China'),
    ('Sweden', 'Japan'),
    ('Belgium', 'Poland'),
]

round1_final_order = {
    ('Sweden', 'Japan') : [
        ('Warlock', 'Hunter'),
        ('Paladin', 'Shaman'),
        ('Priest', 'Rogue'),
        ('Mage', 'Warrior'),
        ('Shaman', 'Mage'),
    ],
    ('Slovakia', 'Israel') : [
        ('Rogue', 'Hunter'),
        ('Mage', 'Priest'),
        ('Shaman', 'Rogue'),
        ('Priest', 'Druid'),
        ('Warlock', 'Paladin'),
    ],
    ('Turkey', 'South Korea') : [
        ('Shaman', 'Warlock'),
        ('Hunter', 'Hunter'),
        ('Priest', 'Druid'),
        ('Warrior', 'Mage'),
        ('Paladin', 'Warrior'),
    ],
    ('Belarus', 'Australia') : [
        ('Rogue', 'Hunter'),
        ('Priest', 'Mage'),
        ('Hunter', 'Warlock'),
        ('Shaman', 'Priest'),
        ('Warrior', 'Paladin'),
    ],
    ('Indonesia', 'Norway') : [
        ('Warlock', 'Warrior'),
        ('Mage', 'Druid'),
        ('Warrior', 'Priest'),
        ('Paladin', 'Paladin'),
        ('Priest', 'Rogue'),
    ],
    ('Bulgaria', 'Malaysia') : [
        ('Druid', 'Warlock'),
        ('Warlock', 'Paladin'),
        ('Warrior', 'Rogue'),
        ('Rogue', 'Warrior'),
        ('Priest', 'Druid'),
    ],
    ('Philippines', 'France') : [
        ('Druid', 'Rogue'),
        ('Priest', 'Shaman'),
        ('Warlock', 'Warlock'),
        ('Paladin', 'Priest'),
        ('Shaman', 'Hunter'),
    ],
    ('Vietnam', 'Italy') : [
        ('Warlock', 'Warrior'),
        ('Priest', 'Hunter'),
        ('Mage', 'Paladin'),
        ('Rogue', 'Rogue'),
        ('Druid', 'Warlock'),
    ],
    ('Belgium', 'Poland') : [
        ('Hunter', 'Shaman'),
        ('Shaman', 'Mage'),
        ('Warlock', 'Warrior'),
        ('Mage', 'Paladin'),
        ('Paladin', 'Warlock'),
    ],
    ('Hungary', 'Thailand') : [
        ('Shaman', 'Hunter'),
        ('Druid', 'Shaman'),
        ('Mage', 'Mage'),
        ('Rogue', 'Rogue'),
        ('Warlock', 'Warrior'),
    ],
    ('Croatia', 'Ukraine') : [
        ('Warlock', 'Warlock'),
        ('Warrior', 'Warrior'),
        ('Hunter', 'Paladin'),
        ('Rogue', 'Rogue'),
        ('Mage', 'Shaman'),
    ],
    ('United States', 'China') : [
        ('Rogue', 'Mage'),
        ('Mage', 'Rogue'),
        ('Shaman', 'Druid'),
        ('Warlock', 'Priest'),
        ('Paladin', 'Warlock'),
    ],
    ('Austria', 'Romania') : [
        ('Warlock', 'Priest'),
        ('Hunter', 'Druid'),
        ('Shaman', 'Shaman'),
        ('Mage', 'Mage'),
        ('Warrior', 'Warlock'),
    ],
    ('Netherlands', 'Germany') : [
        ('Hunter', 'Warlock'),
        ('Paladin', 'Paladin'),
        ('Priest', 'Hunter'),
        ('Warrior', 'Druid'),
        ('Druid', 'Mage'),
    ],
    ('Finland', 'United Kingdom') : [
        ('Mage', 'Shaman'),
        ('Warrior', 'Rogue'),
        ('Shaman', 'Mage'),
        ('Warlock', 'Warrior'),
        ('Priest', 'Paladin'),
    ],
    ('Russia', 'Brazil') : [
        ('Warlock', 'Priest'),
        ('Mage', 'Paladin'),
        ('Shaman', 'Warlock'),
        ('Paladin', 'Warrior'),
        ('Warrior', 'Shaman'),
    ],
    ('Mexico', 'Greece') : [
        ('Priest', 'Druid'),
        ('Rogue', 'Mage'),
        ('Mage', 'Hunter'),
        ('Warrior', 'Priest'),
        ('Hunter', 'Warlock'),
    ],
    ('Czech Republic', 'Canada') : [
        ('Rogue', 'Warlock'),
        ('Shaman', 'Paladin'),
        ('Mage', 'Rogue'),
        ('Priest', 'Mage'),
        ('Warrior', 'Druid'),
    ],
    ('Spain', 'Switzerland') : [
        ('Priest', 'Hunter'),
        ('Druid', 'Mage'),
        ('Paladin', 'Rogue'),
        ('Shaman', 'Warrior'),
        ('Mage', 'Warlock'),
    ],
    ('New Zealand', 'Portugal') : [
        ('Rogue', 'Rogue'),
        ('Mage', 'Paladin'),
        ('Warlock', 'Druid'),
        ('Shaman', 'Mage'),
        ('Hunter', 'Priest'),
    ],
    ('Denmark', 'Peru') : [
        ('Warlock', 'Priest'),
        ('Shaman', 'Mage'),
        ('Mage', 'Warrior'),
        ('Hunter', 'Hunter'),
        ('Priest', 'Warlock'),
    ],
    ('Argentina', 'Singapore') : [
        ('Mage', 'Warlock'),
        ('Warlock', 'Druid'),
        ('Priest', 'Rogue'),
        ('Druid', 'Warrior'),
        ('Shaman', 'Mage'),
    ],
    ('Chile', 'Hong Kong') : [
        ('Paladin', 'Druid'),
        ('Rogue', 'Shaman'),
        ('Druid', 'Rogue'),
        ('Warrior', 'Priest'),
        ('Warlock', 'Mage'),
    ],
    ('Taiwan', 'Kazakhstan') : [
        ('Shaman', 'Rogue'),
        ('Warrior', 'Hunter'),
        ('Druid', 'Shaman'),
        ('Hunter', 'Paladin'),
        ('Rogue', 'Warlock'),
    ],
}

round1_scores = {
    ('Austria', 'Romania')    : (2,3),
    ('Argentina', 'Singapore')    : (0,3),
    ('Russia', 'Brazil')    : (2,3),
    ('Vietnam', 'Italy')    : (2,3),
    ('Netherlands', 'Germany')    : (1,3),
    ('Indonesia', 'Norway')    : (3,1),
    ('Taiwan', 'Kazakhstan')    : (3,2),
    ('Finland', 'United Kingdom')    : (3,2),
    ('Bulgaria', 'Malaysia')    : (3,2),
    ('Belarus', 'Australia')    : (3,1),
    ('Czech Republic', 'Canada')    : (3,2),
    ('New Zealand', 'Portugal')    : (3,2),
    ('Mexico', 'Greece')    : (2,3),
    ('Hungary', 'Thailand')    : (2,3),
    ('Spain', 'Switzerland')    : (3,1),
    ('Philippines', 'France')    : (1,3),
    ('Turkey', 'South Korea')    : (1,3),
    ('Chile', 'Hong Kong')    : (3,1),
    ('Denmark', 'Peru')    : (0,3),
    ('Croatia', 'Ukraine')    : (2,3),
    ('Slovakia', 'Israel')    : (3,1),
    ('United States', 'China')    : (2,3),
    ('Sweden', 'Japan')    : (3,2),
    ('Belgium', 'Poland')    : (1,3),
}
