aggro = [
    # only including large enough sample sizes
    'Evolve Shaman',
    'Midrange Hunter',
    'Deathrattle Hunter',
    'Secret Mage',
    'Prince Rogue',
    'Pirate Warrior',
    'Aggro Druid',
    'Zoolock',
    'Elemental Rogue',
    'Murloc Paladin',
    'Grimestreet Paladin',
]
other = [
    # should be aggro, but low sample
    'Tempo Mage',
    'Aggro Paladin',

    'Highlander Priest',
    'Highlander Mage',
    'Dead Man Warrior',
    'Control Paladin',
    'Mill Rogue',
    'Highlander Warlock',
    'Quest Mage',
    'Control Mage',
    'Big Druid',
    'Taunt Druid',
    'Demon Control Warlock',
    'Resurrect Priest',
    'Dragon Priest',
    'Silence Priest',
    'Handlock',
    'Miracle Rogue',
    'Jade Druid',
    'Quest Rogue',
    'Quest Warrior',
    'Enrage Warrior',
]
