popularities = [
    10.11,
    7.05,
    6.12,
    5.52,
    4.93,
    4.75,
    4.69,
    4.22,
    4.15,
    3.82,
    3.65,
    3.37,
    2.97,
    2.34,
    2.3,
    2.26,
    2.18,
    2.17,
    1.69,
    1.46,
    1.45,
    1.42,
    1.38,
    1.3,
    1.18,
    1.1,
    1.08,
    1.03,
    1,
    0.88,
    0.87,
    0.86 ,
    0.75,
    0.75,
    0.55,
    0.53,
    0.53,
    0.52,
    0.5,
    0.39,
    0.38,
    0.36,
    0.35,
    0.33,
    0.23,
    0.19,
    0.17,
    0.17,
]

archs = [
    "Secret Mage ",
    "Dragon Priest",
    "Spell Hunter",
    "Tempo Rogue",
    "Zoolock",
    "Demonlock",
    "Highlander Priest",
    "Big Priest",
    "Aggro Paladin",
    "Other Hunter",
    "Other Priest",
    "Murloc Paladin",
    "Other Warlock",
    "Kingsbane Rogue",
    "Other Paladin",
    "Jade Druid",
    "Aggro Druid",
    "Secret Hunter",
    "Miracle Rogue",
    "Other Druid",
    "Other Mage",
    "Big Spell Mage",
    "Princelock",
    "Other Rogue",
    "Big Druid",
    "Midrange Hunter",
    "Miracle Druid",
    "Recruit Warrior",
    "Pirate Warrior",
    "Token Shaman",
    "Recruit Hunter",
    "Exodia Mage",
    "Highlander Warlock",
    "Other Warrior",
    "Recruit Druid",
    "Control Mage",
    "Control Paladin",
    "Leyline Mage",
    "Silver Hand Paladin",
    "N'Zoth Paladin",
    "Quest Priest",
    "Quest Rogue",
    "Other Shaman",
    "Shield Warrior",
    "Fatigue Warrior",
    "Elemental Shaman",
    "Elemental Mage",
    "Quest Warrior",
]

frequency = {
    "Secret Mage "            : 10.11,
    "Dragon Priest"           :  7.05,
    "Spell Hunter"            :  6.12,
    "Tempo Rogue"             :  5.52,
    "Zoolock Warlock"         :  4.93,
    "Demonlock Warlock"       :  4.75,
    "Highlander Priest"       :  4.69,
    "Big Priest"              :  4.22,
    "Aggro Paladin"           :  4.15,
    "Other Hunter"            :  3.82,
    "Other Priest"            :  3.65,
    "Murloc Paladin"          :  3.37,
    "Other Warlock"           :  2.97,
    "Kingsbane Rogue"         :  2.34,
    "Other Paladin"           :  2.30,
    "Jade Druid"              :  2.26,
    "Aggro Druid"             :  2.18,
    "Secret Hunter"           :  2.17,
    "Miracle Rogue"           :  1.69,
    "Other Druid"             :  1.46,
    "Other Mage"              :  1.45,
    "Big Spell Mage"          :  1.42,
    "Princelock Warlock"      :  1.38,
    "Other Rogue"             :  1.30,
    "Big Druid"               :  1.18,
    "Midrange Hunter"         :  1.10,
    "Miracle Druid"           :  1.08,
    "Recruit Warrior"         :  1.03,
    "Pirate Warrior"          :  1.00,
    "Token Shaman"            :  0.88,
    "Recruit Hunter"          :  0.87,
    "Exodia Mage"             :  0.86,
    "Highlander Warlock"      :  0.75,
    "Other Warrior"           :  0.75,
    "Recruit Druid"           :  0.55,
    "Control Mage"            :  0.53,
    "Control Paladin"         :  0.53,
    "Leyline Mage"            :  0.52,
    "Silver Hand Paladin"     :  0.50,
    "N'Zoth Paladin"          :  0.39,
    "Quest Priest"            :  0.38,
    "Quest Rogue"             :  0.36,
    "Other Shaman"            :  0.35,
    "Shield Warrior"          :  0.33,
    "Fatigue Warrior"         :  0.23,
    "Elemental Shaman"        :  0.19,
    "Elemental Mage"          :  0.17,
    "Quest Warrior"           :  0.17,
}

#for i,j in zip(archs, popularities):
#    string = '"%s"' % i
#    print "%-25s : %s," % (string,j)
